name: calculator
description: A calculator web app.
version: 1.0.0

environment:
  sdk: ^3.2.3

dependencies:
  math_expressions: ^2.4.0

dev_dependencies:
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.0
  lints: ^2.1.0
